import { VocabularyItem } from '../types';

export const HSK1_TITLES: Record<number, string> = {
  1: 'Chào hỏi (你好)',
  2: 'Cảm ơn (谢谢你)',
  3: 'Tên bạn là gì? (你叫什么名字)',
  4: 'Cô ấy là giáo viên của tôi (她是我的汉语老师)',
  5: 'Con gái cô ấy năm nay 20 tuổi (她女儿今年二十岁)',
  6: 'Tôi biết nói tiếng Trung (我会说汉语)',
  7: 'Hôm nay ngày mấy? (今天几号)',
  8: 'Tôi muốn uống trà (我想喝茶)',
  9: 'Con trai bạn làm việc ở đâu? (你儿子在哪儿工作)',
  10: 'Tôi có thể ngồi đây không? (我能坐这儿吗)',
  11: 'Bây giờ là mấy giờ? (现在几点)',
  12: 'Ngày mai thời tiết thế nào? (明天天气怎么样)',
  13: 'Anh ấy đang học nấu món Trung Quốc (他在学做中国菜呢)',
  14: 'Cô ấy đã mua rất nhiều quần áo (她买了不少衣服)',
  15: 'Tôi đi máy bay đến đây (我是坐飞机来的)'
};

export const HSK1_DATA: Record<number, Partial<VocabularyItem>[]> = {
  1: [
    { word: '你', pronunciation: 'nǐ', meaning: 'anh, chị, bạn (ngôi thứ 2 số ít)', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '好', pronunciation: 'hǎo', meaning: 'tốt, khỏe, ngon', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '您', pronunciation: 'nín', meaning: 'ông, bà, ngài (lịch sự)', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '你们', pronunciation: 'nǐmen', meaning: 'các anh, các chị, các bạn (số nhiều)', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '对不起', pronunciation: 'duìbuqǐ', meaning: 'xin lỗi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '没关系', pronunciation: 'méiguānxi', meaning: 'không có gì, không sao đâu', partOfSpeech: 'v.', grammar: 'Thành ngữ' }
  ],
  2: [
    { word: '谢谢', pronunciation: 'xièxie', meaning: 'cảm ơn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '不', pronunciation: 'bù', meaning: 'không (phủ định)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '不客气', pronunciation: 'búkèqi', meaning: 'đừng khách sáo, không có gì', partOfSpeech: 'v.', grammar: 'Thành ngữ' },
    { word: '再见', pronunciation: 'zàijiàn', meaning: 'tạm biệt, hẹn gặp lại', partOfSpeech: 'v.', grammar: 'Tạm biệt' }
  ],
  3: [
    { word: '叫', pronunciation: 'jiào', meaning: 'tên là, gọi là', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '什么', pronunciation: 'shénme', meaning: 'cái gì, gì', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '名字', pronunciation: 'míngzi', meaning: 'tên', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '我', pronunciation: 'wǒ', meaning: 'tôi, ta, mình', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '是', pronunciation: 'shì', meaning: 'là', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '老师', pronunciation: 'lǎoshī', meaning: 'thầy giáo, cô giáo', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '吗', pronunciation: 'ma', meaning: 'không? (trợ từ nghi vấn)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '学生', pronunciation: 'xuésheng', meaning: 'học sinh, sinh viên', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '人', pronunciation: 'rén', meaning: 'người', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  4: [
    { word: '她', pronunciation: 'tā', meaning: 'cô ấy, bà ấy', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '谁', pronunciation: 'shéi', meaning: 'ai', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '的', pronunciation: 'de', meaning: 'của (trợ từ sở hữu)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '汉语', pronunciation: 'Hànyǔ', meaning: 'tiếng Hán, tiếng Trung', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '哪', pronunciation: 'nǎ', meaning: 'nào', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '国', pronunciation: 'guó', meaning: 'nước, quốc gia', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '呢', pronunciation: 'ne', meaning: 'nhỉ, nhé, còn... (trợ từ tì nghi)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '他', pronunciation: 'tā', meaning: 'anh ấy, ông ấy', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '同学', pronunciation: 'tóngxué', meaning: 'bạn cùng học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '朋友', pronunciation: 'péngyou', meaning: 'bạn bè', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  5: [
    { word: '家', pronunciation: 'jiā', meaning: 'nhà, gia đình', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '有', pronunciation: 'yǒu', meaning: 'có', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '口', pronunciation: 'kǒu', meaning: 'lượng từ chỉ nhân khẩu trong gia đình', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '女儿', pronunciation: 'nǚ\'ér', meaning: 'con gái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '几', pronunciation: 'jǐ', meaning: 'mấy (số lượng dưới 10)', partOfSpeech: 'num.', grammar: 'Số từ' },
    { word: '岁', pronunciation: 'suì', meaning: 'tuổi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '了', pronunciation: 'le', meaning: 'rồi (trợ từ ngữ khí)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '今年', pronunciation: 'jīnián', meaning: 'năm nay', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '多', pronunciation: 'duō', meaning: 'bao nhiêu, nhiều', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '大', pronunciation: 'dà', meaning: 'lớn, to, già', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  6: [
    { word: '会', pronunciation: 'huì', meaning: 'biết (thông qua học tập)', partOfSpeech: 'v.', grammar: 'Động từ năng nguyện' },
    { word: '说', pronunciation: 'shuō', meaning: 'nói', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '妈妈', pronunciation: 'māma', meaning: 'mẹ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '菜', pronunciation: 'cài', meaning: 'món ăn, rau', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '很', pronunciation: 'hěn', meaning: 'rất', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '好吃', pronunciation: 'hǎochī', meaning: 'ngon', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '做', pronunciation: 'zuò', meaning: 'làm, nấu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '写', pronunciation: 'xiě', meaning: 'viết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '汉字', pronunciation: 'Hànzì', meaning: 'chữ Hán', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '字', pronunciation: 'zi', meaning: 'chữ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '怎么', pronunciation: 'zěnme', meaning: 'như thế nào, bằng cách nào', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '读', pronunciation: 'dú', meaning: 'đọc', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  7: [
    { word: '请', pronunciation: 'qǐng', meaning: 'mời, xin', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '问', pronunciation: 'wèn', meaning: 'hỏi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '今天', pronunciation: 'jīntiān', meaning: 'hôm nay', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '号', pronunciation: 'hào', meaning: 'ngày, số', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '月', pronunciation: 'yuè', meaning: 'tháng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '星期', pronunciation: 'xīngqī', meaning: 'tuần, thứ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '昨天', pronunciation: 'zuótiān', meaning: 'hôm qua', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '明天', pronunciation: 'míngtiān', meaning: 'ngày mai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '去', pronunciation: 'qù', meaning: 'đi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '学校', pronunciation: 'xuéxiào', meaning: 'trường học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '看', pronunciation: 'kàn', meaning: 'nhìn, xem, đọc', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '书', pronunciation: 'shū', meaning: 'sách', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  8: [
    { word: '想', pronunciation: 'xiǎng', meaning: 'muốn, nhớ', partOfSpeech: 'v.', grammar: 'Động từ năng nguyện' },
    { word: '喝', pronunciation: 'hē', meaning: 'uống', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '茶', pronunciation: 'chá', meaning: 'trà', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '吃', pronunciation: 'chī', meaning: 'ăn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '米饭', pronunciation: 'mǐfàn', meaning: 'cơm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '下午', pronunciation: 'xiàwǔ', meaning: 'buổi chiều', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '商店', pronunciation: 'shāngdiàn', meaning: 'cửa hàng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '买', pronunciation: 'mǎi', meaning: 'mua', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '个', pronunciation: 'gè', meaning: 'cái, con (lượng từ phổ biến)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '杯子', pronunciation: 'bēizi', meaning: 'cái cốc/ly', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '这', pronunciation: 'zhè', meaning: 'đây, này', partOfSpeech: 'pron.', grammar: 'Đại từ chỉ thị' },
    { word: '多少', pronunciation: 'duōshao', meaning: 'bao nhiêu', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '钱', pronunciation: 'qián', meaning: 'tiền', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '块', pronunciation: 'kuài', meaning: 'đồng (đơn vị tiền tệ)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '那', pronunciation: 'nà', meaning: 'kia, đó', partOfSpeech: 'pron.', grammar: 'Đại từ chỉ thị' }
  ],
  9: [
    { word: '小', pronunciation: 'xiǎo', meaning: 'nhỏ, bé', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '猫', pronunciation: 'māo', meaning: 'con mèo', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '在', pronunciation: 'zài', meaning: 'ở, tại', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '那儿', pronunciation: 'nàr', meaning: 'chỗ kia, ở đó', partOfSpeech: 'pron.', grammar: 'Đại từ chỉ thị' },
    { word: '狗', pronunciation: 'gǒu', meaning: 'con chó', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '椅子', pronunciation: 'yǐzi', meaning: 'cái ghế', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '下面', pronunciation: 'xiàmiàn', meaning: 'phía dưới', partOfSpeech: 'n.', grammar: 'Danh từ phương vị' },
    { word: '哪儿', pronunciation: 'nǎr', meaning: 'ở đâu', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '工作', pronunciation: 'gōngzuò', meaning: 'làm việc, công tác', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '儿子', pronunciation: 'érzi', meaning: 'con trai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '医院', pronunciation: 'yīyuàn', meaning: 'bệnh viện', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '医生', pronunciation: 'yīshēng', meaning: 'bác sĩ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '爸爸', pronunciation: 'bàba', meaning: 'bố, ba', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  10: [
    { word: '桌子', pronunciation: 'zhuōzi', meaning: 'cái bàn', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '上', pronunciation: 'shàng', meaning: 'trên, phía trên', partOfSpeech: 'n.', grammar: 'Danh từ phương vị' },
    { word: '电脑', pronunciation: 'diànnǎo', meaning: 'máy tính', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '和', pronunciation: 'hé', meaning: 'và', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '本', pronunciation: 'běn', meaning: 'quyển, cuốn (lượng từ dùng cho sách)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '里', pronunciation: 'lǐ', meaning: 'trong, bên trong', partOfSpeech: 'n.', grammar: 'Danh từ phương vị' },
    { word: '前面', pronunciation: 'qiánmiàn', meaning: 'phía trước', partOfSpeech: 'n.', grammar: 'Danh từ phương vị' },
    { word: '后面', pronunciation: 'hòumiàn', meaning: 'phía sau', partOfSpeech: 'n.', grammar: 'Danh từ phương vị' },
    { word: '这儿', pronunciation: 'zhèr', meaning: 'chỗ này, ở đây', partOfSpeech: 'pron.', grammar: 'Đại từ chỉ thị' },
    { word: '没有', pronunciation: 'méiyǒu', meaning: 'không có', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '能', pronunciation: 'néng', meaning: 'có thể', partOfSpeech: 'v.', grammar: 'Động từ năng nguyện' },
    { word: '坐', pronunciation: 'zuò', meaning: 'ngồi', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  11: [
    { word: '现在', pronunciation: 'xiànzài', meaning: 'bây giờ, hiện tại', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '点', pronunciation: 'diǎn', meaning: 'giờ', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '分', pronunciation: 'fēn', meaning: 'phút', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '中午', pronunciation: 'zhōngwǔ', meaning: 'buổi trưa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '吃饭', pronunciation: 'chī fàn', meaning: 'ăn cơm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '时候', pronunciation: 'shíhou', meaning: 'thời gian, lúc, khi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '回', pronunciation: 'huí', meaning: 'về, trở về', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '我们', pronunciation: 'wǒmen', meaning: 'chúng tôi, chúng ta', partOfSpeech: 'pron.', grammar: 'Đại từ nhân xưng' },
    { word: '电影', pronunciation: 'diànyǐng', meaning: 'phim', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '住', pronunciation: 'zhù', meaning: 'ở, trú ngụ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '前', pronunciation: 'qián', meaning: 'trước', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  12: [
    { word: '天气', pronunciation: 'tiānqì', meaning: 'thời tiết', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '怎么样', pronunciation: 'zěnmeyàng', meaning: 'thế nào, ra sao', partOfSpeech: 'pron.', grammar: 'Đại từ nghi vấn' },
    { word: '太', pronunciation: 'tài', meaning: 'quá, lắm', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '热', pronunciation: 'rè', meaning: 'nóng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '冷', pronunciation: 'lěng', meaning: 'lạnh', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '下雨', pronunciation: 'xià yǔ', meaning: 'mưa', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '小姐', pronunciation: 'xiǎojiě', meaning: 'cô, tiểu thư', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '来', pronunciation: 'lái', meaning: 'đến, lại', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '身体', pronunciation: 'shēntǐ', meaning: 'thân thể, sức khỏe', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '爱', pronunciation: 'ài', meaning: 'yêu, thích', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '些', pronunciation: 'xiē', meaning: 'một số, một vài', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '水果', pronunciation: 'shuǐguǒ', meaning: 'hoa quả', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '水', pronunciation: 'shuǐ', meaning: 'nước', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  13: [
    { word: '喂', pronunciation: 'wèi', meaning: 'a lô (khi nghe điện thoại)', partOfSpeech: 'int.', grammar: 'Thán từ' },
    { word: '也', pronunciation: 'yě', meaning: 'cũng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '学习', pronunciation: 'xuéxí', meaning: 'học tập, học', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '上午', pronunciation: 'shàngwǔ', meaning: 'buổi sáng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '睡觉', pronunciation: 'shuì jiào', meaning: 'ngủ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '电视', pronunciation: 'diànshì', meaning: 'tivi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '喜欢', pronunciation: 'xǐhuan', meaning: 'thích', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '给', pronunciation: 'gěi', meaning: 'cho', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '打电话', pronunciation: 'dǎ diànhuà', meaning: 'gọi điện thoại', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '吧', pronunciation: 'ba', meaning: 'nhé, đi (trợ từ ngữ khí)', partOfSpeech: 'part.', grammar: 'Trợ từ' }
  ],
  14: [
    { word: '东西', pronunciation: 'dōngxi', meaning: 'đồ đạc, vật phẩm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '一点儿', pronunciation: 'yìdiǎnr', meaning: 'một chút, một ít', partOfSpeech: 'num-m.', grammar: 'Số từ - Lượng từ' },
    { word: '苹果', pronunciation: 'píngguǒ', meaning: 'táo', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '看见', pronunciation: 'kànjiàn', meaning: 'nhìn thấy', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '先生', pronunciation: 'xiānsheng', meaning: 'ông, ngài, chồng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '开', pronunciation: 'kāi', meaning: 'lái (xe), mở', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '车', pronunciation: 'chē', meaning: 'xe', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '回来', pronunciation: 'huílái', meaning: 'trở về', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '分钟', pronunciation: 'fēnzhōng', meaning: 'phút', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '后', pronunciation: 'hòu', meaning: 'sau, phía sau', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '衣服', pronunciation: 'yīfu', meaning: 'quần áo', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '漂亮', pronunciation: 'piàoliang', meaning: 'đẹp', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '啊', pronunciation: 'a', meaning: 'à, ồ (trợ từ ngữ khí)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '少', pronunciation: 'shǎo', meaning: 'ít', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '不少', pronunciation: 'bùshǎo', meaning: 'không ít, nhiều', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '这些', pronunciation: 'zhèxiē', meaning: 'những cái này', partOfSpeech: 'pron.', grammar: 'Đại từ chỉ thị' },
    { word: '都', pronunciation: 'dōu', meaning: 'đều', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ],
  15: [
    { word: '认识', pronunciation: 'rènshi', meaning: 'quen biết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '年', pronunciation: 'nián', meaning: 'năm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '大学', pronunciation: 'dàxué', meaning: 'đại học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '饭店', pronunciation: 'fàndiàn', meaning: 'khách sạn, nhà hàng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '出租车', pronunciation: 'chūzūchē', meaning: 'xe taxi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '一起', pronunciation: 'yìqǐ', meaning: 'cùng nhau', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '高兴', pronunciation: 'gāoxìng', meaning: 'vui vẻ', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '听', pronunciation: 'tīng', meaning: 'nghe', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '飞机', pronunciation: 'fēijī', meaning: 'máy bay', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ]
};
