import { VocabularyItem } from '../types';

export const HSK3_TITLES: Record<number, string> = {
  1: 'Dự định cuối tuần (周末你有什么打算?)',
  2: 'Khi nào anh ấy quay về? (他什么时候回来?)',
  3: 'Trên bàn có rất nhiều thức uống (桌子上放着很多饮料)',
  4: 'Cô ấy luôn cười khi nói chuyện (她总是笑着跟客人说话)',
  5: 'Dạo này em ngày càng béo ra (我最近越来越胖了)',
  6: 'Sao bỗng dưng không tìm thấy? (怎么突然找不到了?)',
  7: 'Tôi và cô ấy quen nhau 5 năm rồi (我跟她都认识五年了)',
  8: 'Em đi đâu thì anh đi đến đó (你去哪儿我就去哪儿)',
  9: 'Tiếng Trung của cô ấy rất tốt (她的汉语说得跟中国人一样好)',
  10: 'Toán khó hơn Lịch sử nhiều (数学比历史难多了)',
  11: 'Đừng quên tắt điều hòa (别忘了把空调关了)',
  12: 'Để đồ quan trọng ở chỗ tôi (把重要的东西放在我这儿吧)',
  13: 'Tôi là đi bộ về (我是走回来的)',
  14: 'Cậu mang trái cây đến đây (你把水果拿过来)',
  15: 'Những câu khác không có vấn đề gì (其他都没什么问题)',
  16: 'Tôi mệt đến nỗi muốn đi ngủ ngay (我现在累得下了班就想睡觉)',
  17: 'Ai cũng có cách chữa khỏi bệnh (谁都有办法看好你的“病”)',
  18: 'Tôi tin họ sẽ đồng ý (我相信他们会同意的)',
  19: 'Anh không nhìn ra được à? (你没看出来吗?)',
  20: 'Mình bị anh ấy ảnh hưởng (我被他影响了)'
};

export const HSK3_DATA: Record<number, Partial<VocabularyItem>[]> = {
  1: [
    { word: '周末', pronunciation: 'zhōumò', meaning: 'cuối tuần', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '打算', pronunciation: 'dǎsuàn', meaning: 'dự định, kế hoạch', partOfSpeech: 'n./v.', grammar: 'Danh từ/Động từ' },
    { word: '跟', pronunciation: 'gēn', meaning: 'với, cùng', partOfSpeech: 'prep./v.', grammar: 'Giới từ' },
    { word: '一直', pronunciation: 'yìzhí', meaning: 'luôn luôn, suốt', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '游戏', pronunciation: 'yóuxì', meaning: 'trò chơi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '作业', pronunciation: 'zuòyè', meaning: 'bài tập', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '着急', pronunciation: 'zháojí', meaning: 'lo lắng, sốt ruột', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '复习', pronunciation: 'fùxí', meaning: 'ôn tập', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '南方', pronunciation: 'nánfāng', meaning: 'phía nam', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '北方', pronunciation: 'běifāng', meaning: 'phía bắc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '面包', pronunciation: 'miànbāo', meaning: 'bánh mì', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '地图', pronunciation: 'dìtú', meaning: 'bản đồ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '搬', pronunciation: 'bān', meaning: 'dọn, chuyển', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  2: [
    { word: '腿', pronunciation: 'tuǐ', meaning: 'chân', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '疼', pronunciation: 'téng', meaning: 'đau', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '脚', pronunciation: 'jiǎo', meaning: 'bàn chân', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '树', pronunciation: 'shù', meaning: 'cây', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '容易', pronunciation: 'róngyì', meaning: 'dễ dàng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '难', pronunciation: 'nán', meaning: 'khó', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '太太', pronunciation: 'tàitai', meaning: 'bà, phu nhân', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '秘书', pronunciation: 'mìshū', meaning: 'thư ký', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '经理', pronunciation: 'jīnglǐ', meaning: 'giám đốc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '办公室', pronunciation: 'bàngōngshì', meaning: 'văn phòng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '辆', pronunciation: 'liàng', meaning: 'chiếc (lượng từ xe cộ)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '楼', pronunciation: 'lóu', meaning: 'tòa nhà, tầng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '拿', pronunciation: 'ná', meaning: 'cầm, lấy', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '把', pronunciation: 'bǎ', meaning: 'chiếc (lượng từ vật có tay cầm)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '伞', pronunciation: 'sǎn', meaning: 'cái ô, dù', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '胖', pronunciation: 'pàng', meaning: 'béo', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '其实', pronunciation: 'qíshí', meaning: 'thực ra', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '瘦', pronunciation: 'shòu', meaning: 'gầy', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  3: [
    { word: '还是', pronunciation: 'háishi', meaning: 'hay là (dùng trong câu hỏi)', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '爬山', pronunciation: 'pá shān', meaning: 'leo núi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '小心', pronunciation: 'xiǎoxīn', meaning: 'cẩn thận', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '条', pronunciation: 'tiáo', meaning: 'chiếc, con (lượng từ vật dài)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '裤子', pronunciation: 'kùzi', meaning: 'quần', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '记得', pronunciation: 'jìde', meaning: 'nhớ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '衬衫', pronunciation: 'chènshān', meaning: 'áo sơ mi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '元', pronunciation: 'yuán', meaning: 'tệ, đồng', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '新鲜', pronunciation: 'xīnxiān', meaning: 'tươi, mới', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '甜', pronunciation: 'tián', meaning: 'ngọt', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '只', pronunciation: 'zhǐ', meaning: 'chỉ', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '饮料', pronunciation: 'yǐnliào', meaning: 'đồ uống', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '或者', pronunciation: 'huòzhě', meaning: 'hoặc là (dùng trong câu trần thuật)', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '舒服', pronunciation: 'shūfu', meaning: 'thoải mái, dễ chịu', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '花', pronunciation: 'huā', meaning: 'hoa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '绿', pronunciation: 'lǜ', meaning: 'màu xanh lá', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  4: [
    { word: '比赛', pronunciation: 'bǐsài', meaning: 'cuộc thi, trận đấu', partOfSpeech: 'n./v.', grammar: 'Danh từ/Động từ' },
    { word: '照片', pronunciation: 'zhàopiàn', meaning: 'bức ảnh', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '年级', pronunciation: 'niánjí', meaning: 'khối lớp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '又', pronunciation: 'yòu', meaning: 'lại, vừa (lại)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '聪明', pronunciation: 'cōngming', meaning: 'thông minh', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '热情', pronunciation: 'rèqíng', meaning: 'nhiệt tình', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '努力', pronunciation: 'nǔlì', meaning: 'nỗ lực, chăm chỉ', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '总是', pronunciation: 'zǒngshì', meaning: 'luôn luôn', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '回答', pronunciation: 'huídá', meaning: 'trả lời', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '超市', pronunciation: 'chāoshì', meaning: 'siêu thị', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '蛋糕', pronunciation: 'dàngāo', meaning: 'bánh kem', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '客人', pronunciation: 'kèrén', meaning: 'khách', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  5: [
    { word: '发烧', pronunciation: 'fā shāo', meaning: 'phát sốt', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '为', pronunciation: 'wèi', meaning: 'vì, cho', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '照顾', pronunciation: 'zhàogù', meaning: 'chăm sóc', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '用', pronunciation: 'yòng', meaning: 'dùng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '感冒', pronunciation: 'gǎnmào', meaning: 'cảm mạo, cảm lạnh', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '季节', pronunciation: 'jìjié', meaning: 'mùa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '当然', pronunciation: 'dāngrán', meaning: 'đương nhiên', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '春', pronunciation: 'chūn', meaning: 'mùa xuân', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '草', pronunciation: 'cǎo', meaning: 'cỏ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '夏', pronunciation: 'xià', meaning: 'mùa hè', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '裙子', pronunciation: 'qúnzi', meaning: 'váy', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '最近', pronunciation: 'zuìjìn', meaning: 'gần đây', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '越', pronunciation: 'yuè', meaning: 'càng', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ],
  6: [
    { word: '眼睛', pronunciation: 'yǎnjing', meaning: 'mắt', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '突然', pronunciation: 'tūrán', meaning: 'đột nhiên', partOfSpeech: 'adj./adv.', grammar: 'Tính từ/Phó từ' },
    { word: '离开', pronunciation: 'líkāi', meaning: 'rời khỏi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '清楚', pronunciation: 'qīngchu', meaning: 'rõ ràng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '刚才', pronunciation: 'gāngcái', meaning: 'vừa nãy', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '帮忙', pronunciation: 'bāng máng', meaning: 'giúp đỡ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '特别', pronunciation: 'tèbié', meaning: 'đặc biệt, vô cùng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '讲', pronunciation: 'jiǎng', meaning: 'nói, giảng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '明白', pronunciation: 'míngbai', meaning: 'hiểu rõ', partOfSpeech: 'adj./v.', grammar: 'Tính từ/Động từ' },
    { word: '锻炼', pronunciation: 'duànliàn', meaning: 'rèn luyện, tập thể dục', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '聊天', pronunciation: 'liáo tiānr', meaning: 'tán gẫu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '睡着', pronunciation: 'shuìzháo', meaning: 'ngủ thiếp đi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '更', pronunciation: 'gèng', meaning: 'hơn nữa, càng hơn', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ],
  7: [
    { word: '同事', pronunciation: 'tóngshì', meaning: 'đồng nghiệp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '以前', pronunciation: 'yǐqián', meaning: 'trước đây', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '银行', pronunciation: 'yínháng', meaning: 'ngân hàng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '久', pronunciation: 'jiǔ', meaning: 'lâu', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '感兴趣', pronunciation: 'gǎn xìngqù', meaning: 'có hứng thú', partOfSpeech: 'v.', grammar: 'Cụm động từ' },
    { word: '结婚', pronunciation: 'jié hūn', meaning: 'kết hôn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '欢迎', pronunciation: 'huānyíng', meaning: 'hoan nghênh', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '迟到', pronunciation: 'chídào', meaning: 'đến muộn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '刻', pronunciation: 'kè', meaning: 'khắc (15 phút)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '差', pronunciation: 'chà', meaning: 'kém, thiếu', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  8: [
    { word: '又', pronunciation: 'yòu', meaning: 'lại (xảy ra rồi)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '满意', pronunciation: 'mǎnyì', meaning: 'hài lòng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '电梯', pronunciation: 'diàntī', meaning: 'thang máy', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '层', pronunciation: 'céng', meaning: 'tầng', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '害怕', pronunciation: 'hàipà', meaning: 'sợ hãi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '熊猫', pronunciation: 'xióngmāo', meaning: 'gấu trúc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '见面', pronunciation: 'jiàn miàn', meaning: 'gặp mặt', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '安静', pronunciation: 'ānjìng', meaning: 'yên tĩnh', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '可乐', pronunciation: 'kělè', meaning: 'coca-cola', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '一会儿', pronunciation: 'yíhuìr', meaning: 'một lát', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '马上', pronunciation: 'mǎshàng', meaning: 'ngay lập tức', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '洗手间', pronunciation: 'xǐshǒujiān', meaning: 'nhà vệ sinh', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  9: [
    { word: '一样', pronunciation: 'yíyàng', meaning: 'giống nhau', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '最后', pronunciation: 'zuìhòu', meaning: 'cuối cùng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '放心', pronunciation: 'fàng xīn', meaning: 'yên tâm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '一定', pronunciation: 'yídìng', meaning: 'nhất định', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '了解', pronunciation: 'liǎojiě', meaning: 'hiểu rõ, tìm hiểu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '先', pronunciation: 'xiān', meaning: 'trước', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '中间', pronunciation: 'zhōngjiān', meaning: 'giữa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '终于', pronunciation: 'zhōngyú', meaning: 'cuối cùng (sau nhiều nỗ lực)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '种', pronunciation: 'zhǒng', meaning: 'loại', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '重要', pronunciation: 'zhòngyào', meaning: 'quan trọng', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  10: [
    { word: '个子', pronunciation: 'gèzi', meaning: 'vóc dáng, chiều cao', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '矮', pronunciation: 'ǎi', meaning: 'thấp', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '历史', pronunciation: 'lìshǐ', meaning: 'lịch sử', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '体育', pronunciation: 'tǐyù', meaning: 'thể dục', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '数学', pronunciation: 'shùxué', meaning: 'toán học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '方便', pronunciation: 'fāngbiàn', meaning: 'thuận tiện', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '骑', pronunciation: 'qí', meaning: 'cưỡi, lái (xe đạp)', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '旧', pronunciation: 'jiù', meaning: 'cũ', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '换', pronunciation: 'huàn', meaning: 'thay đổi, đổi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '附近', pronunciation: 'fùjìn', meaning: 'lân cận, gần đây', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '地方', pronunciation: 'dìfang', meaning: 'địa phương, nơi chốn', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '中介', pronunciation: 'zhōngjiè', meaning: 'môi giới', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  11: [
    { word: '图书馆', pronunciation: 'túshūguǎn', meaning: 'thư viện', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '借', pronunciation: 'jiè', meaning: 'mượn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '词典', pronunciation: 'cídiǎn', meaning: 'từ điển', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '还', pronunciation: 'huán', meaning: 'trả lại', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '会议', pronunciation: 'huìyì', meaning: 'hội nghị, cuộc họp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '结束', pronunciation: 'jiéshù', meaning: 'kết thúc', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '忘记', pronunciation: 'wàngjì', meaning: 'quên', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '空调', pronunciation: 'kōngtiáo', meaning: 'máy điều hòa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '关', pronunciation: 'guān', meaning: 'đóng, tắt', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '地铁', pronunciation: 'dìtiě', meaning: 'tàu điện ngầm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '双', pronunciation: 'shuāng', meaning: 'đôi, cặp', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '筷子', pronunciation: 'kuàizi', meaning: 'đôi đũa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '啤酒', pronunciation: 'píjiǔ', meaning: 'bia', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '瓶子', pronunciation: 'píngzi', meaning: 'cái chai, lọ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '笔记', pronunciation: 'bǐjì', meaning: 'ghi chép', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '习惯', pronunciation: 'xíguàn', meaning: 'thói quen', partOfSpeech: 'n./v.', grammar: 'Danh từ/Động từ' }
  ],
  12: [
    { word: '太阳', pronunciation: 'tàiyáng', meaning: 'mặt trời', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '西', pronunciation: 'xī', meaning: 'phương tây', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '生气', pronunciation: 'shēng qì', meaning: 'tức giận', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '行李箱', pronunciation: 'xínglixiāng', meaning: 'va-li hành lý', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '自己', pronunciation: 'zìjǐ', meaning: 'tự mình, bản thân', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '包', pronunciation: 'bāo', meaning: 'túi, cặp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '发现', pronunciation: 'fāxiàn', meaning: 'phát hiện', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '护照', pronunciation: 'hùzhào', meaning: 'hộ chiếu', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '起飞', pronunciation: 'qǐfēi', meaning: 'cất cánh', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '司机', pronunciation: 'sījī', meaning: 'tài xế', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '教', pronunciation: 'jiāo', meaning: 'dạy', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '画', pronunciation: 'huà', meaning: 'vẽ, tranh', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '需要', pronunciation: 'xūyào', meaning: 'cần, nhu cầu', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '黑板', pronunciation: 'hēibǎn', meaning: 'bảng đen', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  13: [
    { word: '终于', pronunciation: 'zhōngyú', meaning: 'cuối cùng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '爷爷', pronunciation: 'yéye', meaning: 'ông nội', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '礼物', pronunciation: 'lǐwù', meaning: 'quà tặng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '奶奶', pronunciation: 'nǎinai', meaning: 'bà nội', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '遇到', pronunciation: 'yùdào', meaning: 'gặp phải, tình cờ gặp', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '过去', pronunciation: 'guòqu', meaning: 'quá khứ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '一般', pronunciation: 'yìbān', meaning: 'thông thường, bình thường', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '愿意', pronunciation: 'yuànyì', meaning: 'nguyện ý, bằng lòng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '起来', pronunciation: 'qǐlái', meaning: 'đứng dậy, bắt đầu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '应该', pronunciation: 'yīnggāi', meaning: 'nên', partOfSpeech: 'v.', grammar: 'Động từ năng nguyện' },
    { word: '生活', pronunciation: 'shēnghuó', meaning: 'cuộc sống, sinh hoạt', partOfSpeech: 'n./v.', grammar: 'Danh từ/Động từ' },
    { word: '校长', pronunciation: 'xiàozhǎng', meaning: 'hiệu trưởng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '坏', pronunciation: 'huài', meaning: 'hỏng, xấu', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '经常', pronunciation: 'jīngcháng', meaning: 'thường xuyên', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ],
  14: [
    { word: '打扫', pronunciation: 'dǎsǎo', meaning: 'quét dọn', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '干净', pronunciation: 'gānjìng', meaning: 'sạch sẽ', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '然后', pronunciation: 'ránhòu', meaning: 'sau đó', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '冰箱', pronunciation: 'bīngxiāng', meaning: 'tủ lạnh', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '洗澡', pronunciation: 'xǐ zǎo', meaning: 'tắm rửa', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '节目', pronunciation: 'jiémù', meaning: 'tiết mục, chương trình', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '月亮', pronunciation: 'yuèliang', meaning: 'mặt trăng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '像', pronunciation: 'xiàng', meaning: 'giống như', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '盘子', pronunciation: 'pánzi', meaning: 'cái đĩa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '刮风', pronunciation: 'guā fēng', meaning: 'nổi gió, gió thổi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '叔叔', pronunciation: 'shūshu', meaning: 'chú', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '阿姨', pronunciation: 'āyí', meaning: 'dì, cô', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '故事', pronunciation: 'gùshi', meaning: 'câu chuyện', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '声音', pronunciation: 'shēngyīn', meaning: 'âm thanh, tiếng nói', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '菜单', pronunciation: 'càidān', meaning: 'thực đơn', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '简单', pronunciation: 'jiǎndān', meaning: 'đơn giản', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '香蕉', pronunciation: 'xiāngjiāo', meaning: 'chuối tiêu', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  15: [
    { word: '其他', pronunciation: 'qítā', meaning: 'cái khác, người khác', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '口', pronunciation: 'kǒu', meaning: 'miệng, lượng từ người trong gia đình', partOfSpeech: 'n./m.', grammar: 'Danh từ/Lượng từ' },
    { word: '水平', pronunciation: 'shuǐpíng', meaning: 'trình độ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '提高', pronunciation: 'tígāo', meaning: 'nâng cao', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '练习', pronunciation: 'liànxí', meaning: 'luyện tập', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '完成', pronunciation: 'wánchéng', meaning: 'hoàn thành', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '句子', pronunciation: 'jùzi', meaning: 'câu', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '注意', pronunciation: 'zhùyì', meaning: 'chú ý', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '上网', pronunciation: 'shàng wǎng', meaning: 'lên mạng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '除了', pronunciation: 'chúle', meaning: 'ngoài... ra', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '新闻', pronunciation: 'xīnwén', meaning: 'tin tức', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '花', pronunciation: 'huā', meaning: 'tiêu (tiền, thời gian)', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '极', pronunciation: 'jí', meaning: 'cực kỳ, hết sức', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '节日', pronunciation: 'jiérì', meaning: 'ngày lễ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '举行', pronunciation: 'jǔxíng', meaning: 'tổ chức', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '世界', pronunciation: 'shìjiè', meaning: 'thế giới', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '街道', pronunciation: 'jiēdào', meaning: 'đường phố', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '各', pronunciation: 'gè', meaning: 'mỗi, các', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '文化', pronunciation: 'wénhuà', meaning: 'văn hóa', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  16: [
    { word: '城市', pronunciation: 'chéngshì', meaning: 'thành phố', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '如果', pronunciation: 'rúguǒ', meaning: 'nếu như', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '认为', pronunciation: 'rènwéi', meaning: 'cho rằng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '皮鞋', pronunciation: 'píxié', meaning: 'giày da', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '帽子', pronunciation: 'màozi', meaning: 'mũ, nón', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '长', pronunciation: 'zhǎng', meaning: 'trưởng, mọc, lớn lên', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '可爱', pronunciation: 'kě\'ài', meaning: 'đáng yêu', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '米', pronunciation: 'mǐ', meaning: 'mét', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '公斤', pronunciation: 'gōngjīn', meaning: 'kg', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '鼻子', pronunciation: 'bízi', meaning: 'mũi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '头发', pronunciation: 'tóufa', meaning: 'tóc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '检查', pronunciation: 'jiǎnchá', meaning: 'kiểm tra', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '刷牙', pronunciation: 'shuā yá', meaning: 'đánh răng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '关系', pronunciation: 'guānxì', meaning: 'quan hệ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '别人', pronunciation: 'biérén', meaning: 'người khác', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '词语', pronunciation: 'cíyǔ', meaning: 'từ ngữ', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  17: [
    { word: '请假', pronunciation: 'qǐng jià', meaning: 'xin nghỉ phép', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '一共', pronunciation: 'yígòng', meaning: 'tổng cộng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '邻居', pronunciation: 'línjū', meaning: 'hàng xóm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '后来', pronunciation: 'hòulái', meaning: 'sau này, về sau', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '爱好', pronunciation: 'àihào', meaning: 'sở thích', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '办法', pronunciation: 'bànfǎ', meaning: 'cách, biện pháp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '饱', pronunciation: 'bǎo', meaning: 'no', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '为了', pronunciation: 'wèile', meaning: 'để, vì', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '决定', pronunciation: 'juédìng', meaning: 'quyết định', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '选择', pronunciation: 'xuǎnzé', meaning: 'lựa chọn', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '冬', pronunciation: 'dōng', meaning: 'mùa đông', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '必须', pronunciation: 'bìxū', meaning: 'phải, bắt buộc', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '根据', pronunciation: 'gēnjù', meaning: 'của, dựa vào', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '情况', pronunciation: 'qíngkuàng', meaning: 'tình hình', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '口', pronunciation: 'kǒu', meaning: 'miệng, ngụm', partOfSpeech: 'n./m.', grammar: 'Danh từ/Lượng từ' },
    { word: '渴', pronunciation: 'kě', meaning: 'khát', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  18: [
    { word: '向', pronunciation: 'xiàng', meaning: 'về phía, hướng về', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '万', pronunciation: 'wàn', meaning: 'vạn, mười nghìn', partOfSpeech: 'num.', grammar: 'Số từ' },
    { word: '只', pronunciation: 'zhī', meaning: 'con (lượng từ động vật nhỏ)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '嘴', pronunciation: 'zuǐ', meaning: 'miệng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '动物', pronunciation: 'dòngwù', meaning: 'động vật', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '段', pronunciation: 'duàn', meaning: 'đoạn, khoảng', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '不但...而且...', pronunciation: 'búdàn... érqiě...', meaning: 'không những... mà còn...', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '有名', pronunciation: 'yǒumíng', meaning: 'nổi tiếng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '同意', pronunciation: 'tóngyì', meaning: 'đồng ý', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '相信', pronunciation: 'xiāngxìn', meaning: 'tin tưởng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '关于', pronunciation: 'guānyú', meaning: 'về (vấn đề gì)', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '机会', pronunciation: 'jīhuì', meaning: 'cơ hội', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '国家', pronunciation: 'guójiā', meaning: 'quốc gia, đất nước', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '种', pronunciation: 'zhǒng', meaning: 'loại', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '特点', pronunciation: 'tèdiǎn', meaning: 'đặc điểm', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '奇怪', pronunciation: 'qíguài', meaning: 'kỳ quái, lạ lùng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '地', pronunciation: 'de', meaning: 'trợ từ liên kết trạng ngữ và động từ', partOfSpeech: 'part.', grammar: 'Trợ từ' }
  ],
  19: [
    { word: '耳朵', pronunciation: 'ěrduo', meaning: 'tai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '脸', pronunciation: 'liǎn', meaning: 'mặt, khuôn mặt', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '短', pronunciation: 'duǎn', meaning: 'ngắn', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '马', pronunciation: 'mǎ', meaning: 'ngựa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '张', pronunciation: 'zhāng', meaning: 'tấm, bức (lượng từ ảnh, giấy, giường)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '位', pronunciation: 'wèi', meaning: 'vị (lượng từ chỉ người kính trọng)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '蓝', pronunciation: 'lán', meaning: 'màu xanh da trời', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '秋', pronunciation: 'qiū', meaning: 'mùa thu', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '过', pronunciation: 'guò', meaning: 'đã từng (trải qua)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '鸟', pronunciation: 'niǎo', meaning: 'chim', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '哭', pronunciation: 'kū', meaning: 'khóc', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '黄河', pronunciation: 'Huáng Hé', meaning: 'Sông Hoàng Hà', partOfSpeech: 'n.', grammar: 'Danh từ riêng' },
    { word: '船', pronunciation: 'chuán', meaning: 'thuyền, tàu', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '经过', pronunciation: 'jīngguò', meaning: 'đi ngang qua, trải qua', partOfSpeech: 'v./prep.', grammar: 'Động từ/Giới từ' }
  ],
  20: [
    { word: '照相机', pronunciation: 'zhàoxiàngjī', meaning: 'máy chụp ảnh', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '被', pronunciation: 'bèi', meaning: 'bị, được (câu bị động)', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '难过', pronunciation: 'nánguò', meaning: 'buồn, khó chịu', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '东', pronunciation: 'dōng', meaning: 'phía đông', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '信用卡', pronunciation: 'xìnyòngkǎ', meaning: 'thẻ tín dụng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '关心', pronunciation: 'guānxīn', meaning: 'quan tâm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '只有...才...', pronunciation: 'zhǐyǒu... cái...', meaning: 'chỉ có... mới...', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '成绩', pronunciation: 'chéngjì', meaning: 'thành tích, kết quả', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '碗', pronunciation: 'wǎn', meaning: 'bát', partOfSpeech: 'n./m.', grammar: 'Danh từ/Lượng từ' },
    { word: '分', pronunciation: 'fēn', meaning: 'phân biệt, chia', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '解决', pronunciation: 'jiějué', meaning: 'giải quyết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '试', pronunciation: 'shì', meaning: 'thử', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '真正', pronunciation: 'zhēnzhèng', meaning: 'thật sự', partOfSpeech: 'adj./adv.', grammar: 'Tính từ/Phó từ' },
    { word: '多么', pronunciation: 'duōme', meaning: 'bao nhiêu, ngần nào', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ]
};
