import { VocabularyItem } from '../types';

export const HSK2_TITLES: Record<number, string> = {
  1: 'Du lịch (九月去北京旅游最好)',
  2: 'Thói quen (我每天六点起床)',
  3: 'Màu sắc/Vị trí (左边那个红色的是我的)',
  4: 'Công việc (这个工作是他帮我介绍的)',
  5: 'Mua sắm (就买这件吧)',
  6: 'Sức khỏe/Ăn uống (你怎么不吃了?)',
  7: 'Khoảng cách (你家离公司远吗?)',
  8: 'Suy nghĩ (让我想想再告诉你)',
  9: 'Học tập (题太多，我没做完)',
  10: 'Tìm đồ vật (别找了，手机在桌子上呢)',
  11: 'So sánh (他比我大三岁)',
  12: 'Trang phục (你穿得太少了)',
  13: 'Trạng thái (门开着呢)',
  14: 'Kinh nghiệm (你看过那个电影吗?)',
  15: 'Tương lai (新年就要到了)'
};

export const HSK2_DATA: Record<number, Partial<VocabularyItem>[]> = {
  1: [
    { word: '旅游', pronunciation: 'lǚyóu', meaning: 'du lịch', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '觉得', pronunciation: 'juéde', meaning: 'cảm thấy, cho rằng', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '最', pronunciation: 'zuì', meaning: 'nhất', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '为什么', pronunciation: 'wèishénme', meaning: 'tại sao', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '也', pronunciation: 'yě', meaning: 'cũng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '运动', pronunciation: 'yùndòng', meaning: 'vận động, thể thao', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '打篮球', pronunciation: 'dǎ lánqiú', meaning: 'đánh bóng rổ', partOfSpeech: 'v.', grammar: 'Cụm động từ' },
    { word: '踢足球', pronunciation: 'tī zúqiú', meaning: 'đá bóng', partOfSpeech: 'v.', grammar: 'Cụm động từ' },
    { word: '一起', pronunciation: 'yìqǐ', meaning: 'cùng nhau', partOfSpeech: 'adv.', grammar: 'Phó từ' }
  ],
  2: [
    { word: '生病', pronunciation: 'shēng bìng', meaning: 'ốm, bị bệnh', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '每', pronunciation: 'měi', meaning: 'mỗi', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '早上', pronunciation: 'zǎoshang', meaning: 'buổi sáng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '跑步', pronunciation: 'pǎobù', meaning: 'chạy bộ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '起床', pronunciation: 'qǐ chuáng', meaning: 'ngủ dậy', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '药', pronunciation: 'yào', meaning: 'thuốc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '身体', pronunciation: 'shēntǐ', meaning: 'thân thể, sức khỏe', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '出院', pronunciation: 'chū yuàn', meaning: 'xuất viện', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '高', pronunciation: 'gāo', meaning: 'cao', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '米', pronunciation: 'mǐ', meaning: 'mét, gạo', partOfSpeech: 'm./n.', grammar: 'Lượng từ/Danh từ' },
    { word: '知道', pronunciation: 'zhīdào', meaning: 'biết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '休息', pronunciation: 'xiūxi', meaning: 'nghỉ ngơi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '忙', pronunciation: 'máng', meaning: 'bận', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '时间', pronunciation: 'shíjiān', meaning: 'thời gian', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  3: [
    { word: '手表', pronunciation: 'shǒubiǎo', meaning: 'đồng hồ đeo tay', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '千', pronunciation: 'qiān', meaning: 'nghìn', partOfSpeech: 'num.', grammar: 'Số từ' },
    { word: '报纸', pronunciation: 'bàozhǐ', meaning: 'báo chí', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '送', pronunciation: 'sòng', meaning: 'tặng, đưa', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '一下', pronunciation: 'yíxià', meaning: 'một lát, một chút', partOfSpeech: 'num-m.', grammar: 'Số lượng từ' },
    { word: '牛奶', pronunciation: 'niúnǎi', meaning: 'sữa bò', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '房间', pronunciation: 'fángjiān', meaning: 'căn phòng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '丈夫', pronunciation: 'zhàngfu', meaning: 'chồng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '旁边', pronunciation: 'pángbiān', meaning: 'bên cạnh', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '真', pronunciation: 'zhēn', meaning: 'thật sự, thật', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '粉色', pronunciation: 'fěnsè', meaning: 'màu hồng', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '颜色', pronunciation: 'yánsè', meaning: 'màu sắc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '左边', pronunciation: 'zuǒbiān', meaning: 'bên trái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '红色', pronunciation: 'hóngsè', meaning: 'màu đỏ', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  4: [
    { word: '生日', pronunciation: 'shēngrì', meaning: 'sinh nhật', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '快乐', pronunciation: 'kuàilè', meaning: 'vui vẻ, hạnh phúc', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '给', pronunciation: 'gěi', meaning: 'cho', partOfSpeech: 'prep./v.', grammar: 'Giới từ/Động từ' },
    { word: '接', pronunciation: 'jiē', meaning: 'nhận, nghe (điện thoại), đón', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '晚上', pronunciation: 'wǎnshang', meaning: 'buổi tối', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '问', pronunciation: 'wèn', meaning: 'hỏi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '非常', pronunciation: 'fēicháng', meaning: 'vô cùng, rất', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '开始', pronunciation: 'kāishǐ', meaning: 'bắt đầu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '已经', pronunciation: 'yǐjīng', meaning: 'đã, rồi', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '长', pronunciation: 'cháng', meaning: 'dài', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '两', pronunciation: 'liǎng', meaning: 'hai (dùng trước lượng từ)', partOfSpeech: 'num.', grammar: 'Số từ' },
    { word: '帮', pronunciation: 'bāng', meaning: 'giúp đỡ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '介绍', pronunciation: 'jièshào', meaning: 'giới thiệu', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  5: [
    { word: '外面', pronunciation: 'wàimiàn', meaning: 'bên ngoài', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '准备', pronunciation: 'zhǔnbèi', meaning: 'chuẩn bị', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '就', pronunciation: 'jiù', meaning: 'thì, chính (nhấn mạnh)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '鱼', pronunciation: 'yú', meaning: 'con cá', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '吧', pronunciation: 'ba', meaning: 'nhé, đi (trợ từ ngữ khí)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '件', pronunciation: 'jiàn', meaning: 'chiếc/cái (lượng từ quần áo)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '还', pronunciation: 'hái', meaning: 'vẫn, còn', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '可以', pronunciation: 'kěyǐ', meaning: 'có thể', partOfSpeech: 'v.', grammar: 'Động từ năng nguyện' },
    { word: '不错', pronunciation: 'búcuò', meaning: 'không tồi, khá tốt', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '考试', pronunciation: 'kǎoshì', meaning: 'thi cử, bài thi', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '咖啡', pronunciation: 'kāfēi', meaning: 'cà phê', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '对', pronunciation: 'duì', meaning: 'đối với', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '以后', pronunciation: 'yǐhòu', meaning: 'sau này, sau khi', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  6: [
    { word: '门', pronunciation: 'mén', meaning: 'cửa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '外', pronunciation: 'wài', meaning: 'ngoài', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '自行车', pronunciation: 'zìxíngchē', meaning: 'xe đạp', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '羊肉', pronunciation: 'yángròu', meaning: 'thịt cừu, thịt dê', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '好吃', pronunciation: 'hǎochī', meaning: 'ngon', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '面条', pronunciation: 'miàntiáo', meaning: 'mì sợi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '因为', pronunciation: 'yīnwèi', meaning: 'vì, bởi vì', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '所以', pronunciation: 'suǒyǐ', meaning: 'cho nên', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '游泳', pronunciation: 'yóuyǒng', meaning: 'bơi lội', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '经常', pronunciation: 'jīngcháng', meaning: 'thường xuyên', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '公斤', pronunciation: 'gōngjīn', meaning: 'kg', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '姐姐', pronunciation: 'jiějie', meaning: 'chị gái', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  7: [
    { word: '教室', pronunciation: 'jiàoshì', meaning: 'lớp học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '机场', pronunciation: 'jīchǎng', meaning: 'sân bay', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '路', pronunciation: 'lù', meaning: 'đường xá, lối đi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '离', pronunciation: 'lí', meaning: 'cách (khoảng cách)', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '公司', pronunciation: 'gōngsī', meaning: 'công ty', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '远', pronunciation: 'yuǎn', meaning: 'xa', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '公共汽车', pronunciation: 'gōnggòng qìchē', meaning: 'xe buýt', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '小时', pronunciation: 'xiǎoshí', meaning: 'tiếng đồng hồ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '慢', pronunciation: 'màn', meaning: 'chậm', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '快', pronunciation: 'kuài', meaning: 'nhanh', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '过', pronunciation: 'guò', meaning: 'trải qua, ăn (tết), đón (sinh nhật)', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '走', pronunciation: 'zǒu', meaning: 'đi, rời đi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '到', pronunciation: 'dào', meaning: 'đến', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  8: [
    { word: '再', pronunciation: 'zài', meaning: 'lại, nữa', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '让', pronunciation: 'ràng', meaning: 'để cho, bảo, nhường', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '告诉', pronunciation: 'gàosu', meaning: 'nói, cho biết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '等', pronunciation: 'děng', meaning: 'chờ đợi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '找', pronunciation: 'zhǎo', meaning: 'tìm kiếm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '事情', pronunciation: 'shìqing', meaning: 'việc, sự việc', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '服务员', pronunciation: 'fúwùyuán', meaning: 'nhân viên phục vụ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '白', pronunciation: 'bái', meaning: 'trắng', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '黑', pronunciation: 'hēi', meaning: 'đen', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '贵', pronunciation: 'guì', meaning: 'đắt, quý', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  9: [
    { word: '错', pronunciation: 'cuò', meaning: 'sai', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '从', pronunciation: 'cóng', meaning: 'từ (địa điểm/thời gian)', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '跳舞', pronunciation: 'tiào wǔ', meaning: 'nhảy múa', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '第一', pronunciation: 'dì-yī', meaning: 'thứ nhất', partOfSpeech: 'num.', grammar: 'Số từ' },
    { word: '希望', pronunciation: 'xīwàng', meaning: 'hy vọng', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' },
    { word: '问题', pronunciation: 'wèntí', meaning: 'vấn đề, câu hỏi', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '欢迎', pronunciation: 'huānyíng', meaning: 'hoan nghênh, chào đón', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '上班', pronunciation: 'shàng bān', meaning: 'đi làm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '懂', pronunciation: 'dǒng', meaning: 'hiểu', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '完', pronunciation: 'wán', meaning: 'xong, hết', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '题', pronunciation: 'tí', meaning: 'đề bài, câu hỏi', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  10: [
    { word: '课', pronunciation: 'kè', meaning: 'bài học, tiết học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '帮助', pronunciation: 'bāngzhù', meaning: 'giúp đỡ', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '别', pronunciation: 'bié', meaning: 'đừng', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '哥哥', pronunciation: 'gēge', meaning: 'anh trai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '鸡蛋', pronunciation: 'jīdàn', meaning: 'trứng gà', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '西瓜', pronunciation: 'xīguā', meaning: 'dưa hấu', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '正在', pronunciation: 'zhèngzài', meaning: 'đang', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '手机', pronunciation: 'shǒujī', meaning: 'điện thoại di động', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '洗', pronunciation: 'xǐ', meaning: 'rửa, giặt', partOfSpeech: 'v.', grammar: 'Động từ' }
  ],
  11: [
    { word: '唱歌', pronunciation: 'chàng gē', meaning: 'hát', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '男', pronunciation: 'nán', meaning: 'nam, con trai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '女', pronunciation: 'nǚ', meaning: 'nữ, con gái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '孩子', pronunciation: 'háizi', meaning: 'đứa trẻ, con cái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '右边', pronunciation: 'yòubiān', meaning: 'bên phải', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '比', pronunciation: 'bǐ', meaning: 'so với', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '便宜', pronunciation: 'piányi', meaning: 'rẻ', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '说话', pronunciation: 'shuō huà', meaning: 'nói chuyện', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '可能', pronunciation: 'kěnéng', meaning: 'có lẽ, có thể', partOfSpeech: 'adv./v.', grammar: 'Phó từ/Động từ' },
    { word: '去年', pronunciation: 'qùnián', meaning: 'năm ngoái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '姓', pronunciation: 'xìng', meaning: 'họ', partOfSpeech: 'v./n.', grammar: 'Động từ/Danh từ' }
  ],
  12: [
    { word: '得', pronunciation: 'de', meaning: 'trợ từ liên kết bổ ngữ chỉ trạng thái', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '妻子', pronunciation: 'qīzi', meaning: 'vợ', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '雪', pronunciation: 'xuě', meaning: 'tuyết', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '度', pronunciation: 'dù', meaning: 'độ (nhiệt độ)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '穿', pronunciation: 'chuān', meaning: 'mặc', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '进', pronunciation: 'jìn', meaning: 'vào', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '弟弟', pronunciation: 'dìdi', meaning: 'em trai', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '近', pronunciation: 'jìn', meaning: 'gần', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ],
  13: [
    { word: '着', pronunciation: 'zhe', meaning: 'trợ từ động thái (biểu thị sự tiếp diễn)', partOfSpeech: 'part.', grammar: 'Trợ từ' },
    { word: '手', pronunciation: 'shǒu', meaning: 'tay', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '拿', pronunciation: 'ná', meaning: 'cầm, nắm', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '铅笔', pronunciation: 'qiānbǐ', meaning: 'bút chì', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '班', pronunciation: 'bān', meaning: 'lớp học', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '长', pronunciation: 'zhǎng', meaning: 'trưởng, mọc (lớn lên)', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '笑', pronunciation: 'xiào', meaning: 'cười', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '宾馆', pronunciation: 'bīnguǎn', meaning: 'khách sạn', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '一直', pronunciation: 'yìzhí', meaning: 'thẳng, luôn luôn', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '往', pronunciation: 'wǎng', meaning: 'về phía', partOfSpeech: 'prep.', grammar: 'Giới từ' },
    { word: '路口', pronunciation: 'lùkǒu', meaning: 'ngã tư, lối vào', partOfSpeech: 'n.', grammar: 'Danh từ' }
  ],
  14: [
    { word: '意思', pronunciation: 'yìsi', meaning: 'ý nghĩa, thú vị', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '但是', pronunciation: 'dànshì', meaning: 'nhưng', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '虽然', pronunciation: 'suīrán', meaning: 'mặc dù', partOfSpeech: 'conj.', grammar: 'Liên từ' },
    { word: '次', pronunciation: 'cì', meaning: 'lần (lượng từ)', partOfSpeech: 'm.', grammar: 'Lượng từ' },
    { word: '玩儿', pronunciation: 'wánr', meaning: 'chơi', partOfSpeech: 'v.', grammar: 'Động từ' },
    { word: '晴', pronunciation: 'qíng', meaning: 'nắng, trời quang', partOfSpeech: 'adj.', grammar: 'Tính từ' },
    { word: '百', pronunciation: 'bǎi', meaning: 'trăm', partOfSpeech: 'num.', grammar: 'Số từ' }
  ],
  15: [
    { word: '日', pronunciation: 'rì', meaning: 'ngày, mặt trời', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '新年', pronunciation: 'xīnnián', meaning: 'năm mới', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '票', pronunciation: 'piào', meaning: 'vé', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '火车站', pronunciation: 'huǒchēzhàn', meaning: 'ga tàu hỏa', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '大家', pronunciation: 'dàjiā', meaning: 'mọi người', partOfSpeech: 'pron.', grammar: 'Đại từ' },
    { word: '更', pronunciation: 'gèng', meaning: 'hơn (so sánh)', partOfSpeech: 'adv.', grammar: 'Phó từ' },
    { word: '妹妹', pronunciation: 'mèimei', meaning: 'em gái', partOfSpeech: 'n.', grammar: 'Danh từ' },
    { word: '阴', pronunciation: 'yīn', meaning: 'âm, trời râm', partOfSpeech: 'adj.', grammar: 'Tính từ' }
  ]
};
